"""rename location

Revision ID: f47759574bfb
Revises: 84ce957cd2da
Create Date: 2024-10-04 17:55:08.859285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47759574bfb'
down_revision = '84ce957cd2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###
